version: "3.9"
services:
  autoshopapi:
    build: .
    depends_on: 
      mariadb:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file: 
      - .env
  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: autoshop
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10