/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `autoshop` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `autoshop`;

CREATE TABLE IF NOT EXISTS `hits_spotify` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `COMBO` varchar(500) NOT NULL DEFAULT '0',
  `COUNTRY` varchar(500) NOT NULL DEFAULT '0',
  `ADDRESS` varchar(500) NOT NULL DEFAULT '0',
  `LINK` varchar(500) NOT NULL DEFAULT '0',
  `INVITES_LEFT` int(11) DEFAULT NULL,
  `SOLD_COUNT` int(11) DEFAULT 0,
  `DATE_ADDED` datetime DEFAULT curdate(),
  `LAST_SOLD` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=305 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contact_method` varchar(50) DEFAULT NULL,
  `contact_info` varchar(255) DEFAULT NULL,
  `paste_url` varchar(50) DEFAULT NULL,
  `transaction_id` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `date` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
